# .travis.yml

language: cpp
osx_image: xcode10
dist: xenial


# Add-ons: specify apt packages for Linux
addons:
  apt:
   sources: &add-sources
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:jonathonf/ffmpeg-3'
      #- george-edison55-precise-backports
      #- boost-latest
   packages: &common-packages
      # - g++-6
      # - g++-7
      - libgif-dev
      - libopenjpeg-dev
      - libfreetype6-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libavutil-dev
      - python-numpy
      - libraw-dev
      - ninja-build
      - libfreetype6-dev
      # - libjpeg-turbo8-dev
   packages: &common-boost-packages
      - libboost1.58-dev
      - libboost-filesystem1.58
      - libboost-regex1.58
      - libboost-system1.58
      - libboost-thread1.58


cache:
    ccache: true
    apt: true
    directories:
      - $HOME/.ccache

before_install:
    - source src/build-scripts/ci-startup.bash
    - export WHICHGCC=${WHICHGCC:="7"}
    - if [ "$CXX" == "g++" ]; then export CXX="g++-${WHICHGCC}" ; fi

install:
    - if [ $TRAVIS_OS_NAME == osx ] ; then
          source src/build-scripts/install_homebrew_deps.bash ;
      elif [ $TRAVIS_OS_NAME == linux ] ; then
          if [ "$BUILD_CMAKE" == "1" ] ; then
              source src/build-scripts/build_cmake.bash ;
          fi ;
          CXX="ccache $CXX" source src/build-scripts/build_openexr.bash ;
          CXX="ccache $CXX" source src/build-scripts/build_ocio.bash ;
      fi
    - export OPENIMAGEIO_MAKEFLAGS="$OPENIMAGEIO_MAKEFLAGS DEBUG= USE_PYTHON=0 OIIO_BUILD_TESTS=0"
    - export SITE=travis
    - source src/build-scripts/build_openimageio.bash

# before_script:

script:
    - src/build-scripts/ci-build-and-test.bash



branches:
  only:
    - master
    - /RB-/
    - /lg-/

matrix:
    fast_finish: true
    exclude:
      - os: osx
        compiler: gcc
      - os: linux
        compiler: clang

    include:
      - name: "Linux C++11, gcc6"
        os: linux
        compiler: gcc
        env: USE_CPP=11 WHICHGCC=6
        addons:
          apt:
            sources: *add-sources
            packages:
              - *common-packages
              - *common-boost-packages
              - g++-6

      - name: "Linux C++14, gcc7"
        os: linux
        compiler: gcc
        env: USE_CPP=14 WHICHGCC=7
        addons:
          apt:
            sources: *add-sources
            packages:
              - *common-packages
              - *common-boost-packages
              - g++-7

      - name: "Mac (latest Apple clang, python 3.7)"
        os: osx
        compiler: clang
        env: PYTHON_VERSION=3.7

      - name: "Mac py27 (latest Apple clang, python 2.7)"
        os: osx
        compiler: clang
        env: PYTHON_VERSION=2.7




#notifications:
#    email:
#        recipients:
#        on_success: change
#        on_failure: always
