# Copyright Contributors to the Proto project.
# SPDX-License-Identifier: BSD-3-Clause
# https://github.com/lgritz/proto-project

name: CI

on:
  push:
    # Skip jobs when only documentation files are changed
    paths-ignore:
      - '**.md'
      - '**.rst'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'
  # schedule:
  #   # Full nightly build
  #   - cron: "0 8 * * *"


jobs:

  vfxplatform-2020:
    name: "Linux VFX Platform 2020: gcc6/C++14 py3.7 boost-1.70 exr-2.4"
    runs-on: ubuntu-latest
    container:
      image: aswf/ci-osl:2020
    env:
      CXX: g++
      CC: gcc
      CMAKE_CXX_STANDARD: 14
      PYTHON_VERSION: 3.7
      USE_SIMD: avx
    steps:
      - uses: actions/checkout@v2
      - name: Prepare ccache timestamp
        id: ccache_cache_keys
        run: |
          echo "::set-output name=date::`date -u +'%Y-%m-%dT%H:%M:%SZ'`"
      - name: ccache
        id: ccache
        uses: actions/cache@v2
        with:
          path: /tmp/ccache
          key: ${{ github.job }}-${{ steps.ccache_cache_keys.outputs.date }}
          restore-keys: |
            ${{ github.job }}-
      - name: setup
        run: |
            src/build-scripts/ci-startup.bash
      - name: dependencies
        run: |
            src/build-scripts/gh-installdeps.bash
      - name: Build
        run: |
            src/build-scripts/ci-build.bash
      - name: Testsuite
        run: |
            src/build-scripts/ci-test.bash
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ github.job }}
          path: |
            build/*/testsuite/*/*.*
            build/*/CMake*.{txt,log}

  vfxplatform-2021:
    # Test what's anticipated to be VFX Platform 2021 -- mainly, that means
    # gcc9 and C++17.
    name: "Linux VFX Platform 2021: gcc9/C++17 py3.7 boost-1.70 exr-2.5"
    runs-on: ubuntu-18.04
    container:
      image: aswf/ci-osl:2021
    env:
      CXX: g++
      CC: gcc
      CMAKE_CXX_STANDARD: 17
      PYTHON_VERSION: 3.7
      USE_SIMD: avx2,f16c
    steps:
      - uses: actions/checkout@v2
      - name: Prepare ccache timestamp
        id: ccache_cache_keys
        run: |
          echo "::set-output name=date::`date -u +'%Y-%m-%dT%H:%M:%SZ'`"
      - name: ccache
        id: ccache
        uses: actions/cache@v2
        with:
          path: /tmp/ccache
          key: ${{ github.job }}-${{ steps.ccache_cache_keys.outputs.date }}
          restore-keys: |
            ${{ github.job }}-
      - name: setup
        run: |
            src/build-scripts/ci-startup.bash
      - name: dependencies
        run: |
            src/build-scripts/gh-installdeps.bash
      - name: Build
        run: |
            src/build-scripts/ci-build.bash
      - name: Testsuite
        run: |
            src/build-scripts/ci-test.bash
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ github.job }}
          path: |
            build/*/testsuite/*/*.*
            build/*/CMake*.{txt,log}

  linux-latest-releases:
    # Test against latest supported releases of toolchain and dependencies.
    name: "Linux latest releases: gcc10 C++17 avx2 exr2.5"
    runs-on: ubuntu-18.04
    env:
      CXX: g++-10
      CMAKE_CXX_STANDARD: 17
      USE_SIMD: avx2,f16c
      OPENEXR_VERSION: master
      OPENIMAGEIO_VERSION: master
      PYBIND11_VERSION: v2.6.2
      # PYBIND11_VERSION: master
      MY_CMAKE_FLAGS: -DBUILD_FMT_VERSION=master
    steps:
      - uses: actions/checkout@v2
      - name: Prepare ccache timestamp
        id: ccache_cache_keys
        run: |
          echo "::set-output name=date::`date -u +'%Y-%m-%dT%H:%M:%SZ'`"
      - name: ccache
        id: ccache
        uses: actions/cache@v2
        with:
          path: /tmp/ccache
          key: ${{ github.job }}-${{ steps.ccache_cache_keys.outputs.date }}
          restore-keys: |
            ${{ github.job }}-
      - name: setup
        run: |
            src/build-scripts/ci-startup.bash
      - name: dependencies
        run: |
            src/build-scripts/gh-installdeps.bash
      - name: Build
        run: |
            src/build-scripts/ci-build.bash
      - name: Testsuite
        run: |
            src/build-scripts/ci-test.bash
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ github.job }}
          path: |
            build/*/testsuite/*/*.*
            build/*/CMake*.{txt,log}

  macos-py38:
    name: "Mac py38"
    runs-on: macOS-latest
    env:
      CXX: clang++
      PYTHON_VERSION: 3.8
      CMAKE_CXX_STANDARD: 14
      ENABLE_FIELD3D: OFF
    steps:
      - uses: actions/checkout@v2
      - name: Prepare ccache timestamp
        id: ccache_cache_keys
        run: |
          echo "::set-output name=date::`date -u +'%Y-%m-%dT%H:%M:%SZ'`"
      - name: ccache
        id: ccache
        uses: actions/cache@v2
        with:
          path: /Users/runner/.ccache
          key: ${{ github.job }}-${{ steps.ccache_cache_keys.outputs.date }}
          restore-keys: |
            ${{ github.job }}-
      - name: Build setup
        run: |
            src/build-scripts/ci-startup.bash
      - name: Dependencies
        run: |
            src/build-scripts/install_homebrew_deps.bash
            brew install openimageio
      - name: Build
        run: |
            export PYTHONPATH=/usr/local/lib/python${PYTHON_VERSION}/site-packages:$PYTHONPATH
            src/build-scripts/ci-build.bash
      - name: Testsuite
        run: |
            src/build-scripts/ci-test.bash
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ github.job }}
          path: |
            build/*/testsuite/*/*.*
            build/*/CMake*.{txt,log}

  windows-vs2019:
    name: "Windows VS2019"
    runs-on: windows-2019
    env:
      PYTHON_VERSION: 3.7
      CMAKE_GENERATOR: "Visual Studio 16 2019"
      OPENEXR_VERSION: v2.5.5
      OIIO_CTEST_FLAGS: "--timeout 120 --repeat after-timeout:5"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v1
      - name: Build setup
        shell: bash
        run: |
            src/build-scripts/ci-startup.bash
      - name: Dependencies
        shell: bash
        run: |
            src/build-scripts/gh-win-installdeps.bash
      - name: Build
        shell: bash
        run: |
            src/build-scripts/ci-build.bash
      - name: Testsuite
        shell: bash
        run: |
            src/build-scripts/ci-test.bash
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ github.job }}
          path: |
            build/*/testsuite/*/*.*
            build/*/CMake*.{txt,log}

  clang-format:
    # Test formatting. This test entry doesn't do a full build, it just runs
    # clang-format on everything, and passes if nothing is misformatted.
    # Upon failure, the build artifact will be the full source code with the
    # formatting fixed (diffs will also appear in the console output).
    name: "clang-format verification"
    runs-on: ubuntu-18.04
    container:
      image: aswf/ci-osl:2021-clang10
    env:
      BUILDTARGET: clang-format
      PYTHON_VERSION: 3.7
    steps:
      - uses: actions/checkout@v2
      - name: Build setup
        run: |
            src/build-scripts/ci-startup.bash
      - name: Dependencies
        run: |
            src/build-scripts/gh-installdeps.bash
      - name: Build
        run: |
            src/build-scripts/ci-build.bash
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ github.job }}
          path: src/*/*.{cpp,h}
